version: "3.8"

services:
  wizard-deployment:
    container_name: pg-wizard
    image: postgres:latest
    environment:
      - POSTGRES_DB=wizard
      - POSTGRES_USER=wizardadmin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432